/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_devlinuxuser_JKey */

#ifndef _Included_io_github_devlinuxuser_JKey
#define _Included_io_github_devlinuxuser_JKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_devlinuxuser_JKey
 * Method:    readKey
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_io_github_devlinuxuser_JKey_readKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
